window.isMobile=!1;if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){window.isMobile=!0}
window.isiOS=!1;if(/iPhone|iPad|iPod/i.test(navigator.userAgent)){window.isiOS=!0}
window.isiOSVersion='';if(window.isiOS){var version=(navigator.appVersion).match(/OS (\d+)_(\d+)_?(\d+)?/);if(version!==null){window.isiOSVersion=[parseInt(version[1],10),parseInt(version[2],10),parseInt(version[3]||0,10)]}}
window.isiOSChrome=navigator.userAgent.match('CriOS')?!0:!1;window.isSafari=!1;if(/^((?!chrome|android).)*safari/i.test(navigator.userAgent)){window.isSafari=!0}
window.isSafariVersion='';if(window.isSafari){var version=(navigator.appVersion).match(/Version\/(\d+)\.(\d+)\.?(\d+)? Safari/);if(version!==null){window.isSafariVersion=[parseInt(version[1],10),parseInt(version[2],10),parseInt(version[3]||0,10)]}}
window.isIE=!!document.documentMode;window.browserLang=(window.navigator.userLanguage||window.navigator.language).toUpperCase().slice(0,2);window.tildaBrowserLang=window.browserLang;function t_throttle(fn,threshhold,scope){var last;var deferTimer;threshhold||(threshhold=250);return function(){var context=scope||this;var now=+new Date();var args=arguments;if(last&&now<last+threshhold){clearTimeout(deferTimer);deferTimer=setTimeout(function(){last=now;fn.apply(context,args)},threshhold)}else{last=now;fn.apply(context,args)}}}
function t670_init(recid,isEditMode){var rec=document.getElementById('rec'+recid);if(!rec)return;var image=rec.querySelector('.t-img');if(image){if(image.complete){t670_addImageEvents(recid,isEditMode)}else{image.addEventListener('load',function(){t670_addImageEvents(recid,isEditMode)});image.addEventListener('error',function(){t670_addImageEvents(recid,isEditMode)})}}else{t670_addImageEvents(recid,isEditMode)}}
function t670_addImageEvents(recid,isEditMode){var rec=document.getElementById('rec'+recid);t670_imageHeight(rec);t670_show(rec);t670_hide(rec);t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid)});if(isEditMode){t_onFuncLoad('t_slds_UpdateSliderHeight',function(){t_slds_UpdateSliderHeight(recid)});t_onFuncLoad('t_slds_UpdateSliderArrowsHeight',function(){t_slds_UpdateSliderArrowsHeight(recid)})}
var wrapper=rec.querySelector('.t670');if(wrapper){wrapper.addEventListener('displayChanged',function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)});t_onFuncLoad('t_slds_positionArrows',function(){t_slds_positionArrows(recid)})})}}
function t670_show(rec){var playBtns=rec.querySelectorAll('.t670__play');Array.prototype.forEach.call(playBtns,function(play){var itemWrap=play.closest('.t670__imgwrapper');var image=itemWrap.querySelector('.t-slds__bgimg');var videoWrap=itemWrap.querySelector('.t670__wrap-video');var videoLazy=videoWrap.querySelector('.t-video-lazyload');play.addEventListener('click',function(event){event.preventDefault();event.stopPropagation();t_onFuncLoad('t_video_lazyload__addVideo',function(){videoWrap.style.display='block';image.style.opacity=0;t_video_lazyload__addVideo(videoLazy)})})})}
function t670_hide(rec){var videoWraps=rec.querySelectorAll('.t670__wrap-video');var videos=rec.querySelectorAll('.t670__wrap-video .t-video-lazyload');rec.addEventListener('updateSlider',function(){Array.prototype.forEach.call(videoWraps,function(videoWrap){videoWrap.display.style='none'});Array.prototype.forEach.call(videos,function(video){video.innerHTML=''})})}
function t670_imageHeight(rec){var images=rec.querySelectorAll('.t670__separator');Array.prototype.forEach.call(images,function(img){var width=parseInt(img.getAttribute('data-slider-image-width'))||0;var height=parseInt(img.getAttribute('data-slider-image-height'))||0;var ratio=height/width;var padding=ratio*100;img.style.paddingBottom=padding+'%'})}
function t678_onSuccess(form){t_onFuncLoad('t_forms__onSuccess',function(){t_forms__onSuccess(form)})}
function t890_init(recId,offset){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t890');if(!container)return;var windowOffset=offset||window.innerHeight;rec.setAttribute('data-animationappear','off');rec.style.opacity=1;window.addEventListener('scroll',t_throttle(function(){if(window.pageYOffset>windowOffset){container.style.display='block'}else{t890__fadeOut(container)}},200));var isSafari=/^((?!chrome|android).)*safari/i.test(navigator.userAgent);rec.addEventListener('click',function(e){if(e.target.closest('.t890__arrow')){isSafari?t890__animateScrollPolyfill(0):t890__scrollToTop()}})}
function t890__fadeOut(el){if(el.style.display==='none')return;var opacity=1;var timer=setInterval(function(){el.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){clearInterval(timer);el.style.display='none';el.style.opacity=null}},20)}
function t890__scrollToTop(){if(window.isIE){window.scrollTo(0,0)}else{window.scrollTo({left:0,top:0,behavior:'smooth',})}}
function t890__animateScrollPolyfill(target){var documentHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);var bottomViewportPoint=documentHeight-document.documentElement.clientHeight;if(target>bottomViewportPoint)target=bottomViewportPoint;if(target===window.pageYOffset)return!1;var currentPosition=window.pageYOffset;var step=(target-currentPosition)/30;var difference=window.pageYOffset;var timerID=setInterval(function(){difference+=step;window.scrollTo(0,difference);document.body.setAttribute('data-scrollable','true');if((target-currentPosition<0&&window.pageYOffset<=target)||(target-currentPosition>0&&window.pageYOffset>=target)){clearInterval(timerID);document.body.removeAttribute('data-scrollable')}},10)}
function t875_init(){if(document.layers){document.captureEvents(Event.MOUSEDOWN)}
document.onmousedown=t875_click;document.oncontextmenu=function(event){event=event||window.event;var sender=event.target||event.srcElement;if(sender&&(sender.tagName.match(/INPUT|TEXTAREA/i)||sender.hasAttribute('contenteditable')||(sender.parentElement&&sender.parentElement.hasAttribute('contenteditable')))){return}else{return!1}};t875_preventSelection(document);t875_preventUserSelect()}
function t875_preventUserSelect(){var oldStyle=document.body.getAttribute('style');document.body.style.cssText=oldStyle+'-ms-user-select: none;'+'-moz-user-select: none;'+'-webkit-user-select: none;'+'user-select: none;'+'-webkit-touch-callout: none;'}
function t875_click(event){t875_returnPrevent(event);if(document.all){if(event.button===2){return!1}}
if(document.layers){if(event.which===3){return!1}}}
function t875_preventSelection(element){var preventSelection=!1;t875_addHandler(element,'mousemove',function(){if(preventSelection){t875_removeSelection()}});t875_addHandler(element,'mousedown',function(event){event=event||window.event;var sender=event.target||event.srcElement;preventSelection=sender&&!sender.tagName.match(/INPUT|TEXTAREA/i)&&!sender.hasAttribute('contenteditable')&&sender.parentElement&&!sender.parentElement.hasAttribute('contenteditable')});t875_addHandler(element,'mouseup',function(){if(preventSelection){t875_removeSelection()}
preventSelection=!1});t875_addHandler(element,'keydown',t875_killCtrlA);t875_addHandler(element,'keyup',t875_killCtrlA);t875_addHandler(element,'keydown',t875_killCtrlU);t875_addHandler(element,'keyup',t875_killCtrlU);t875_addHandler(element,'keydown',t875_killAltCmdI);t875_addHandler(element,'keyup',t875_killAltCmdI);t875_addHandler(element,'keydown',t875_killCtrlShiftI);t875_addHandler(element,'keyup',t875_killCtrlShiftI)}
function t875_addHandler(element,event,handler){if(element.attachEvent){element.attachEvent('on'+event,handler)}else if(element.addEventListener){element.addEventListener(event,handler,!1)}}
function t875_removeSelection(){if(window.getSelection){window.getSelection().removeAllRanges()}else if(document.selection&&document.selection.clear){document.selection.clear()}}
function t875_killCtrlU(event){t875_returnPrevent(event);var key=event.keyCode||event.which;if((event.ctrlKey&&key=='U'.charCodeAt(0))||(event.altKey&&event.metaKey&&(key=='U'.charCodeAt(0)||key=='u'.charCodeAt(0)))){if(event.preventDefault){event.preventDefault()}else{event.returnValue=!1}}}
function t875_killAltCmdI(event){t875_returnPrevent(event);var key=event.keyCode||event.which;if(event.altKey&&event.metaKey&&(key=='I'.charCodeAt(0)||key=='i'.charCodeAt(0))){if(event.preventDefault){event.preventDefault()}else{event.returnValue=!1}}}
function t875_killCtrlShiftI(event){t875_returnPrevent(event);var key=event.keyCode||event.which;if(event.shiftKey&&event.ctrlKey&&(key=='I'.charCodeAt(0)||key=='i'.charCodeAt(0))){if(event.preventDefault){event.preventDefault()}else{event.returnValue=!1}}}
function t875_killCtrlA(event){event=event||window.event;var sender=event.target||event.srcElement;if(sender&&(sender.tagName.match(/INPUT|TEXTAREA|BUTTON/i)||sender.hasAttribute('contenteditable')||(sender.parentElement&&sender.parentElement.hasAttribute('contenteditable')))){return}
var key=event.keyCode||event.which;if((event.ctrlKey&&key=='A'.charCodeAt(0))||(event.metaKey&&key=='A'.charCodeAt(0))){t875_removeSelection();if(event.preventDefault){event.preventDefault()}else{event.returnValue=!1}}}
function t875_returnPrevent(event){event=event||window.event;var sender=event.target||event.srcElement;if(sender&&(sender.tagName.match(/INPUT|TEXTAREA/i)||sender.hasAttribute('contenteditable')||(sender.parentElement&&sender.parentElement.hasAttribute('contenteditable')))){return}}
function t849_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var togglers=rec.querySelectorAll('.t849__header');var isLazy=document.getElementById('allrecords').getAttribute('data-tilda-lazy');var accordion=rec.querySelector('.t849__accordion');if(accordion){accordion=accordion.getAttribute('data-accordion')}else{accordion='false'}
var cachedHeight=0;var cachedTop=0;Array.prototype.forEach.call(togglers,function(toggler){toggler.addEventListener('click',function(){var target=toggler;var content=target.nextElementSibling;var triggerButton=target.querySelector('.t849__trigger-button');if(accordion==='true'){Array.prototype.forEach.call(togglers,function(header){if(target!==header){header.classList.remove('t849__opened');t849_slideUp(header.nextElementSibling,target)}})}
if(triggerButton){var isExpanded=triggerButton.getAttribute('aria-expanded')==='true';triggerButton.setAttribute('aria-expanded',!isExpanded);content.hidden=isExpanded}
target.classList.toggle('t849__opened');target.style.pointerEvents='none';t849_slideToggle(target.nextElementSibling,target);if(window.lazy==='y'||isLazy==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})});function t849_slideToggle(target,triggerElement,duration){if(!target)return;if(!duration&&duration!==0)duration=300;if(window.getComputedStyle(target).display==='none'){return t849_slideDown(target,triggerElement,duration)}else{cachedHeight=0;return t849_slideUp(target,triggerElement,duration)}}
function t849_slideUp(target,triggerElement,duration){if(!target)return;if(!duration&&duration!==0)duration=300;target.style.transitionProperty='height, margin, padding';target.style.transitionDuration=duration+'ms';target.style.boxSizing='border-box';target.style.height=target.offsetHeight+'px';target.offsetHeight;target.style.overflow='hidden';target.style.height='0';target.style.paddingTop='0';target.style.paddingBottom='0';target.style.marginTop='0';target.style.marginBottom='0';setTimeout(function(){triggerElement.style.pointerEvents='auto';target.style.display='none';target.style.height='';target.style.paddingTop='';target.style.paddingBottom='';target.style.marginTop='';target.style.marginBottom='';target.style.overflow='';target.style.transitionDuration='';target.style.transitionProperty=''},duration)}
function t849_slideDown(target,triggerElement,duration){if(!target)return;if(!duration&&duration!==0)duration=300;target.style.display='';var cashedDisplay=window.getComputedStyle(target).display;if(cashedDisplay==='none')cashedDisplay='block';target.style.display=cashedDisplay;var targetHeight=target.offsetHeight;var targetTop=target.offsetTop;if(window.visualViewport){var visibleTop=targetTop-window.visualViewport.pageTop;if(cachedTop&&accordion==='true'&&targetTop>cachedTop&&window.scrollY>cachedTop){window.scrollTo(window.scrollX,targetTop-cachedHeight-visibleTop)}}
target.style.overflow='hidden';target.style.height='0';target.style.paddingTop='0';target.style.paddingBottom='0';target.style.marginTop='0';target.style.marginBottom='0';target.offsetHeight;target.style.boxSizing='border-box';target.style.transitionProperty='height, margin, padding';target.style.transitionDuration=duration+'ms';target.style.height=targetHeight+'px';target.style.paddingTop='';target.style.paddingBottom='';target.style.marginTop='';target.style.marginBottom='';setTimeout(function(){triggerElement.style.pointerEvents='auto';target.style.height='';target.style.overflow='';target.style.transitionDuration='';target.style.transitionProperty='';cachedHeight=targetHeight;cachedTop=targetTop},duration)}}
var t776_POPUP_SHOWED_EVENT_NAME='catalog:popupShowed';var t776_POPUP_CLOSED_EVENT_NAME='catalog:popupClosed';function t776__init(recid){setTimeout(function(){t_onFuncLoad('t_prod__init',function(){t_prod__init(recid)});t776_initPopup(recid);t776__hoverZoom_init(recid);t776__updateLazyLoad(recid);t776__alignButtons_init(recid);t_onFuncLoad('t_store_addProductQuantityEvents',function(){t776_initProductQuantity(recid)});var event=document.createEvent('HTMLEvents');event.initEvent('twishlist_addbtn',!0,!1);document.body.dispatchEvent(event)},500)}
function t776_initProductQuantity(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var productList=rec.querySelectorAll('.t776__col, .t776__product-full');Array.prototype.forEach.call(productList,function(product){t_store_addProductQuantityEvents(product)})}
function t776__showMore(recid){var rec=document.querySelector('#rec'+recid+' .t776');if(!rec)return;var cardsCount=parseInt(rec.getAttribute('data-show-count'),10);if(isNaN(cardsCount)||cardsCount<1)return;var showMoreButton=rec.querySelector('.t776__showmore');if(!showMoreButton)return;if(!showMoreButton.querySelector('td').textContent){showMoreButton.querySelector('td').textContent=t776__dict()}
var firstProductCard=rec.querySelector('.t776__col');if(!firstProductCard)return;var productCards=rec.querySelectorAll('.t776__col');var cardsLenght=productCards.length;if(!window.getComputedStyle)return;if(cardsLenght>cardsCount){showMoreButton.style.display='inline-block'}
Array.prototype.forEach.call(productCards,function(card){card.style.display='none'});t776__showSeparator(rec,cardsCount);for(var i=0;i<cardsCount;i++){if(productCards[i]){productCards[i].style.removeProperty('display')}}
window.addEventListener('resize',function(){Array.prototype.forEach.call(productCards,function(card){card.style.display='none'});for(var i=0;i<cardsCount;i++){if(productCards[i]){productCards[i].style.removeProperty('display')}}});var showedCardsCount=0;showMoreButton.addEventListener('click',function(){Array.prototype.forEach.call(productCards,function(product){if(product.style.display===''){showedCardsCount++}});cardsCount+=showedCardsCount;for(var i=0;i<cardsCount;i++){if(productCards[i]){productCards[i].style.removeProperty('display')}}
if(cardsCount>=cardsLenght){showMoreButton.style.display='none'}
t776__showSeparator(rec,cardsCount);if(rec.querySelector('[data-buttons-v-align]')){t776__alignButtons(recid)}
if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}
function t776__showSeparator(rec,cardsCount){if(window.jQuery&&rec instanceof jQuery){rec=rec.get(0)}
var allSeparators=rec.querySelectorAll('.t776__separator_number');Array.prototype.forEach.call(allSeparators,function(separator){separator.classList.add('t776__separator_hide');if(separator.getAttribute('data-product-separator-number')<=cardsCount){separator.classList.remove('t776__separator_hide')}})}
function t776__dict(){var dictionary={EN:'Load more',RU:'Загрузить еще',FR:'Charger plus',DE:'Mehr laden',ES:'Carga más',PT:'Carregue mais',UK:'Завантажити ще',JA:'もっと読み込む',ZH:'裝載更多',};var language=window.browserLang;return dictionary[language]?dictionary[language]:dictionary.EN}
function t776__alignButtons_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;if(!rec.querySelector('[data-buttons-v-align]')){return}
try{t776__alignButtons(recid);if(document.querySelector('.t-records').getAttribute('data-tilda-mode')==='edit'){setInterval(function(){t776__alignButtons(recid)},200)}
window.addEventListener('resize',t_throttle(function(){if(typeof window.noAdaptive!=='undefined'&&window.noAdaptive===!0&&window.isMobile){return}
t776__alignButtons(recid)}));var wrapperBlock=rec.querySelector('.t776');if(wrapperBlock){wrapperBlock.addEventListener('displayChanged',function(){t776__alignButtons(recid)})}
if(window.isMobile){window.addEventListener('orientationchange',function(){t776__alignButtons(recid)})}}catch(error){console.log('buttons-v-align error: '+error.message)}}
function t776__alignButtons(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var maxHeight=0;var wrappers=rec.querySelectorAll('.t776__textwrapper');var container=rec.querySelector('.t776__parent');if(container){var productInRow=parseInt(container.getAttribute('data-blocks-per-row'),10)}
var mobileView=window.innerWidth<=480;var tableView=window.innerWidth<=960&&window.innerWidth>480;var mobileOneRow=window.innerWidth<=960&&rec.querySelector('.t776__container_mobile-flex');var mobileTwoItemsInRow=window.innerWidth<=480&&rec.querySelector('.t776 .mobile-two-columns');if(mobileView){productInRow=1}
if(tableView){productInRow=2}
if(mobileTwoItemsInRow){productInRow=2}
if(mobileOneRow){productInRow=999999}
var count=1;var wrappersInRow=[];Array.prototype.forEach.call(wrappers,function(wrapper){wrapper.style.height='auto';if(productInRow===1){wrapper.style.height='auto'}else{wrappersInRow.push(wrapper);if(wrapper.offsetHeight>maxHeight){maxHeight=wrapper.offsetHeight}
Array.prototype.forEach.call(wrappersInRow,function(wrapperInRow){wrapperInRow.style.height=maxHeight+'px'});if(count===productInRow){count=0;maxHeight=0;wrappersInRow=[]}
count++}})}
function t776__hoverZoom_init(recid){if(window.isMobile){return}
var rec=document.getElementById('rec'+recid);if(!rec)return;var parent=rec.querySelector('.t776__parent');try{if(parent&&parent.getAttribute('data-hover-zoom')!=='yes'){return}
var hoverScript='https://static.tildacdn.com/js/tilda-hover-zoom-1.0.min.js';if(document.querySelector("script[src^='"+hoverScript+"']")){t_onFuncLoad('t_hoverZoom_init',function(){t_hoverZoom_init(recid)})}else{var script=document.createElement('script');script.type='text/javascript';script.src=hoverScript;script.onload=function(){setTimeout(function(){t_hoverZoom_init(recid)},500)};script.onerror=function(error){console.log('Upload script error: ',error)};document.head.appendChild(script)}}catch(error){console.log('Zoom image init error: '+error.message)}}
function t776__updateLazyLoad(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var scrollContainer=rec.querySelector(' .t776__container_mobile-flex');var currentMode=document.querySelector('.t-records').getAttribute('data-tilda-mode');if(scrollContainer&&currentMode!=='edit'&&currentMode!=='preview'){scrollContainer.addEventListener('scroll',t_throttle(function(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}))}}
function t776_initPopup(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var openerLink=rec.querySelectorAll('[href^="#prodpopup"]');var popup=rec.querySelector('.t-popup');Array.prototype.forEach.call(openerLink,function(link){var product=link.closest('.js-product');var productLid=product.getAttribute('data-product-lid');var productLinks=document.querySelectorAll('.r a[href$="#!/tproduct/'+recid+'-'+productLid+'"]');Array.prototype.forEach.call(productLinks,function(productLink){productLink.addEventListener('click',function(){if(rec.querySelector('[data-product-lid="'+productLid+'"]')){var linkToPopup=product.querySelector('[href^="#prodpopup"]');if(linkToPopup){var event=document.createEvent('HTMLEvents');event.initEvent('click',!0,!1);linkToPopup.dispatchEvent(event)}}})});link.addEventListener('click',clickOnceHandler,!1);function clickOnceHandler(event){event.preventDefault();var product=link.closest('.js-product');var productLid=product.getAttribute('data-product-lid');t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid+' #t776__product-'+productLid+'')});link.removeEventListener('click',clickOnceHandler,!1)}
link.addEventListener('click',showPopupHandler,!1);function showPopupHandler(event){event.preventDefault();if(event.target.classList.contains('t1002__addBtn')||event.target.parentNode.classList.contains('t1002__addBtn')){return}
t776_showPopup(recid);var product=link.closest('.js-product');var productLid=product.getAttribute('data-product-lid');var allProducts=popup.querySelectorAll('.js-product');Array.prototype.forEach.call(allProducts,function(product){product.style.display='none'});var productFull=popup.querySelector('.js-product[data-product-lid="'+productLid+'"]');if(productFull){productFull.style.display='block'}
var analitics=popup.getAttribute('data-track-popup');if(analitics&&productFull&&window.Tilda){var productName=productFull.querySelector('.js-product-name');if(productName){var virtualTitle=productName.textContent;if(!virtualTitle){virtualTitle='prod'+productLid}
Tilda.sendEventToStatistics(analitics,virtualTitle)}}
var currentUrl=window.location.href;if(currentUrl.indexOf('#!/tproduct/')===-1&&currentUrl.indexOf('%23!/tproduct/')===-1){if(typeof history.replaceState!=='undefined'){window.history.replaceState('','',window.location.href+'#!/tproduct/'+recid+'-'+productLid)}}
t776_updateSlider(recid+' #t776__product-'+productLid);if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}});if(document.querySelectorAll('#record'+recid).length===0){t776_checkUrl(recid)}
if(popup&&popup.hasAttribute('data-fixed-button')){t776_fixedPopupButton(recid)}}
function t776_checkUrl(recid){var currentUrl=window.location.href;var tprodIndex=(currentUrl.indexOf('#!/tproduct/')+1||currentUrl.indexOf('%23!/tproduct/')+1||currentUrl.indexOf('#%21%2Ftproduct%2F')+1||currentUrl.indexOf('#!%2Ftproduct%2F')+1||currentUrl.indexOf('%23%21%2Ftproduct%2F')+1)-1;if(tprodIndex!==-1){var currentUrl=currentUrl.substring(tprodIndex,currentUrl.length);var curProdLid=currentUrl.substring(currentUrl.indexOf('-')+1,currentUrl.length);if(curProdLid){var curProdLidMatch=curProdLid.match(/([0-9]+)/g);if(curProdLidMatch){curProdLid=curProdLidMatch[0]}}
if(currentUrl.indexOf(recid)===-1)return;var rec=document.getElementById('rec'+recid);if(!rec)return;if(currentUrl.indexOf(recid)!==0&&rec.querySelector('[data-product-lid="'+curProdLid+'"]')){var currentLink=rec.querySelector('[data-product-lid="'+curProdLid+'"] [href^="#prodpopup"]');var event=document.createEvent('HTMLEvents');event.initEvent('click',!0,!1);if(currentLink){currentLink.dispatchEvent(event)}}}}
function t776_updateSlider(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;t_onFuncLoad('t_slds_SliderWidth',function(){t_slds_SliderWidth(recid)});var slider=rec.querySelector('.t-slds__container');var paddingLeft=parseInt(slider.style.paddingLeft)||0;var paddingRight=parseInt(slider.style.paddingRight)||0;var sliderWrapper=rec.querySelector('.t-slds__items-wrapper');var sliderWidth=slider.clientWidth-(paddingLeft+paddingRight);var position=parseFloat(sliderWrapper.getAttribute('data-slider-pos'));sliderWrapper.style.transform='translate3d(-'+sliderWidth*position+'px, 0, 0)';t_onFuncLoad('t_slds_UpdateSliderHeight',function(){t_slds_UpdateSliderHeight(recid)});t_onFuncLoad('t_slds_UpdateSliderArrowsHeight',function(){t_slds_UpdateSliderArrowsHeight(recid)})}
function t776_showPopup(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var popup=rec.querySelector('.t-popup');popup.style.display='block';setTimeout(function(){popup.querySelector('.t-popup__container').classList.add('t-popup__container-animated');popup.classList.add('t-popup_show');t_triggerEvent(popup,t776_POPUP_SHOWED_EVENT_NAME)},50);setTimeout(function(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}},300);var body=document.body;if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');body.classList.add('t-body_popupshowed');var event=document.createEvent('HTMLEvents');event.initEvent('twishlist_addbtn',!0,!1);body.dispatchEvent(event);popup.addEventListener('mousedown',function(event){var windowWidth=window.innerWidth;var maxScrollBarWidth=17;var windowWithoutScrollBar=windowWidth-maxScrollBarWidth;if(event.clientX>windowWithoutScrollBar){return}
if(event.target===this){t776_closePopup(body,popup)}});var closeButtons=rec.querySelectorAll('.t-popup__close, .t776__close-text');Array.prototype.forEach.call(closeButtons,function(button){button.addEventListener('click',function(){t776_closePopup(body,popup)})});document.addEventListener('keydown',function(event){var isGalleryShowedOldLib=document.body.classList.contains('t-zoomer__show');if(isGalleryShowedOldLib)return;var isGalleryShowedNewLib=document.body.classList.contains('t-zoomer__active');if(isGalleryShowedNewLib)return;var isPopupShowed=document.body.classList.contains('t-body_popupshowed');if(!isPopupShowed)return;if(popup&&popup.classList.contains('t-popup_show')){if(event.keyCode===27){t776_closePopup(body,popup)}}});if(window.isSafari){setTimeout(function(){popup.scrollTop=1})}}
function t776_closePopup(body,popup){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');body.classList.remove('t-body_popupshowed');popup.classList.remove('t-popup_show');var event=document.createEvent('HTMLEvents');event.initEvent('twishlist_addbtn',!0,!1);body.dispatchEvent(event);var currentUrl=window.location.href;var indexToRemove=currentUrl.indexOf('#!/tproduct/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&indexToRemove<0){indexToRemove=currentUrl.indexOf('%23!/tproduct/')}
currentUrl=currentUrl.substring(0,indexToRemove);setTimeout(function(){popup.scrollTop=0;popup.style.display='none';if(typeof history.replaceState!=='undefined'){window.history.replaceState('','',currentUrl)}},300);t_triggerEvent(popup,t776_POPUP_CLOSED_EVENT_NAME)}
function t776_fixedPopupButton(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var MOBILE_MAX_WIDTH=560;var popup=rec.querySelector('.t-popup');var popupContainer=popup.querySelector('.t-popup__container');var btnWrappers=rec.querySelectorAll('.t776__btn-wrapper');Array.prototype.forEach.call(btnWrappers,function(el){el.classList.add('t776__btn-wrapper-fixed')});function addStyle(){popupContainer.style.paddingBottom='90px';popupContainer.style.cssText+=';transform:none !important;'}
function resetStyle(){popupContainer.style.paddingBottom='';popupContainer.style.transform=''}
function handleResize(){if(window.innerWidth>MOBILE_MAX_WIDTH){resetStyle();return}
addStyle()}
if(window.isMobile){window.addEventListener('orientationchange',handleResize)}
popup.addEventListener(t776_POPUP_SHOWED_EVENT_NAME,function(){setTimeout(function(){handleResize()})});popup.addEventListener(t776_POPUP_CLOSED_EVENT_NAME,function(){resetStyle()});window.addEventListener('resize',handleResize)}